### ISSUE TITLE
Change default branch & content to accomodate glitch

### ISSUE THREAD

**Issue by ThomasG77** [freeCodeCamp/boilerplate-mongomongoose#11]
When importing in Glitch from a repository, Glitch expects to get the master branch.
In this repo, the useful content is in gomix branch not master branch.
To bypass this, I had to fork the repo, change the content of master branch with the one in gomix branch and change default branch in my fork to make things work.
It should not be this way IMO. Can you make the changes?

**Comment by Bam92** [comment]
I can't have a good structure with Glitch. When I open the link, sometimes I find `package.json` nor `server.json`. And sometimes I find them, but `server.json` is empty and asks me to run `refresh`.
What is the best way to use Glitch for this project?

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
