### ISSUE TITLE
Unable to finish the model.findOne() lesson as getting "Server Error" as output, able to finish the next lesson without any error.

### ISSUE THREAD

**Issue by mechbullgt** [freeCodeCamp/boilerplate-mongomongoose#13]
Hi Team FCC, 
Before everything thanks for putting this amazing course online, and thanks to all the contributors for their efforts in keeping it alive.

I'm hereby sharing some screenshots I took as that would help in reproducing the issue, I'm getting a error code 500 on the file server.js, I tried to debug but not able to resolve as the issue in somewhere on the VM128 file AFAIK. As a part of the test the person is getting created on the database but somehow the validation is not happening and hence the lesson is not getting submitter.

Any help here would be appreciated.

Screenshot: 1/2
![freeCodeCamp-findOne-500-issue](https://user-images.githubusercontent.com/23336355/57567994-dc837180-73fe-11e9-8c3e-54df12e5fd3b.png)

Screenshot: 2/2
![500issue-screenshot2of2](https://user-images.githubusercontent.com/23336355/57568001-ec9b5100-73fe-11e9-8c54-85f360dc5ddb.png)

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
